//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.FactoryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", ConfigurationName="FactoryServiceReference.FactoryService")]
    public interface FactoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool addMemberToMemberAccess(long arg0, int arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void saveFactory(long arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void deleteFactory(long arg0, int arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string createMachine(long arg0, int arg1, int arg2, int arg3, Client.FactoryServiceReference.direction arg4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool moveMachine(long arg0, string arg1, int arg2, int arg3);
        
        // CODEGEN: Parameter "arg1" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.FactoryServiceReference.deleteMachinesResponse deleteMachines(Client.FactoryServiceReference.deleteMachinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Client.FactoryServiceReference.position getMachinePosition(long arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void scriptMachine(long arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getMachineScript(long arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool resizeFactory(long arg0, int arg1, int arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int getAreaWidth(long arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int getAreaHeight(long arg0);
        
        // CODEGEN: Parameter "arg1" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.FactoryServiceReference.setMachineCapacityResponse setMachineCapacity(Client.FactoryServiceReference.setMachineCapacityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int getMachineCapacity(long arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void sendChatMessage(long arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int getEmptyConsumerTickCount(long arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void setEmptyConsumerTickCount(long arg0, string arg1, int arg2);
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Client.FactoryServiceReference.getScriptableMachinesResponse getScriptableMachines(Client.FactoryServiceReference.getScriptableMachinesRequest request);
        
        // CODEGEN: Parameter "arg1" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.FactoryServiceReference.rotateMachinesLeftResponse rotateMachinesLeft(Client.FactoryServiceReference.rotateMachinesLeftRequest request);
        
        // CODEGEN: Parameter "arg1" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.FactoryServiceReference.rotateMachinesRightResponse rotateMachinesRight(Client.FactoryServiceReference.rotateMachinesRightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Client.FactoryServiceReference.machineMap getFactory(long arg0);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/")]
    public enum direction {
        
        /// <remarks/>
        NORTH,
        
        /// <remarks/>
        SOUTH,
        
        /// <remarks/>
        EAST,
        
        /// <remarks/>
        WEST,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteMachines", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class deleteMachinesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg1;
        
        public deleteMachinesRequest() {
        }
        
        public deleteMachinesRequest(long arg0, string[] arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteMachinesResponse", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class deleteMachinesResponse {
        
        public deleteMachinesResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/")]
    public partial class position : object, System.ComponentModel.INotifyPropertyChanged {
        
        private direction directionField;
        
        private bool directionFieldSpecified;
        
        private int xField;
        
        private int yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public direction direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool directionSpecified {
            get {
                return this.directionFieldSpecified;
            }
            set {
                this.directionFieldSpecified = value;
                this.RaisePropertyChanged("directionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/")]
    public partial class machineMap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private machineMapEntry[] mapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public machineMapEntry[] map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("map");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/")]
    public partial class machineMapEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private position valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public position value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMachineCapacity", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class setMachineCapacityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int arg2;
        
        public setMachineCapacityRequest() {
        }
        
        public setMachineCapacityRequest(long arg0, string[] arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMachineCapacityResponse", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class setMachineCapacityResponse {
        
        public setMachineCapacityResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScriptableMachines", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class getScriptableMachinesRequest {
        
        public getScriptableMachinesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getScriptableMachinesResponse", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class getScriptableMachinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int>[] @return;
        
        public getScriptableMachinesResponse() {
        }
        
        public getScriptableMachinesResponse(System.Nullable<int>[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rotateMachinesLeft", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class rotateMachinesLeftRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg1;
        
        public rotateMachinesLeftRequest() {
        }
        
        public rotateMachinesLeftRequest(long arg0, string[] arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rotateMachinesLeftResponse", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class rotateMachinesLeftResponse {
        
        public rotateMachinesLeftResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rotateMachinesRight", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class rotateMachinesRightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] arg1;
        
        public rotateMachinesRightRequest() {
        }
        
        public rotateMachinesRightRequest(long arg0, string[] arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rotateMachinesRightResponse", WrapperNamespace="http://service.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class rotateMachinesRightResponse {
        
        public rotateMachinesRightResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FactoryServiceChannel : Client.FactoryServiceReference.FactoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FactoryServiceClient : System.ServiceModel.ClientBase<Client.FactoryServiceReference.FactoryService>, Client.FactoryServiceReference.FactoryService {
        
        public FactoryServiceClient() {
        }
        
        public FactoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FactoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addMemberToMemberAccess(long arg0, int arg1, string arg2) {
            return base.Channel.addMemberToMemberAccess(arg0, arg1, arg2);
        }
        
        public void saveFactory(long arg0) {
            base.Channel.saveFactory(arg0);
        }
        
        public void deleteFactory(long arg0, int arg1) {
            base.Channel.deleteFactory(arg0, arg1);
        }
        
        public string createMachine(long arg0, int arg1, int arg2, int arg3, Client.FactoryServiceReference.direction arg4) {
            return base.Channel.createMachine(arg0, arg1, arg2, arg3, arg4);
        }
        
        public bool moveMachine(long arg0, string arg1, int arg2, int arg3) {
            return base.Channel.moveMachine(arg0, arg1, arg2, arg3);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.FactoryServiceReference.deleteMachinesResponse Client.FactoryServiceReference.FactoryService.deleteMachines(Client.FactoryServiceReference.deleteMachinesRequest request) {
            return base.Channel.deleteMachines(request);
        }
        
        public void deleteMachines(long arg0, string[] arg1) {
            Client.FactoryServiceReference.deleteMachinesRequest inValue = new Client.FactoryServiceReference.deleteMachinesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Client.FactoryServiceReference.deleteMachinesResponse retVal = ((Client.FactoryServiceReference.FactoryService)(this)).deleteMachines(inValue);
        }
        
        public Client.FactoryServiceReference.position getMachinePosition(long arg0, string arg1) {
            return base.Channel.getMachinePosition(arg0, arg1);
        }
        
        public void scriptMachine(long arg0, string arg1, string arg2) {
            base.Channel.scriptMachine(arg0, arg1, arg2);
        }
        
        public string getMachineScript(long arg0, string arg1) {
            return base.Channel.getMachineScript(arg0, arg1);
        }
        
        public bool resizeFactory(long arg0, int arg1, int arg2) {
            return base.Channel.resizeFactory(arg0, arg1, arg2);
        }
        
        public int getAreaWidth(long arg0) {
            return base.Channel.getAreaWidth(arg0);
        }
        
        public int getAreaHeight(long arg0) {
            return base.Channel.getAreaHeight(arg0);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.FactoryServiceReference.setMachineCapacityResponse Client.FactoryServiceReference.FactoryService.setMachineCapacity(Client.FactoryServiceReference.setMachineCapacityRequest request) {
            return base.Channel.setMachineCapacity(request);
        }
        
        public void setMachineCapacity(long arg0, string[] arg1, int arg2) {
            Client.FactoryServiceReference.setMachineCapacityRequest inValue = new Client.FactoryServiceReference.setMachineCapacityRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Client.FactoryServiceReference.setMachineCapacityResponse retVal = ((Client.FactoryServiceReference.FactoryService)(this)).setMachineCapacity(inValue);
        }
        
        public int getMachineCapacity(long arg0, string arg1) {
            return base.Channel.getMachineCapacity(arg0, arg1);
        }
        
        public void sendChatMessage(long arg0, string arg1) {
            base.Channel.sendChatMessage(arg0, arg1);
        }
        
        public int getEmptyConsumerTickCount(long arg0, string arg1) {
            return base.Channel.getEmptyConsumerTickCount(arg0, arg1);
        }
        
        public void setEmptyConsumerTickCount(long arg0, string arg1, int arg2) {
            base.Channel.setEmptyConsumerTickCount(arg0, arg1, arg2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.FactoryServiceReference.getScriptableMachinesResponse Client.FactoryServiceReference.FactoryService.getScriptableMachines(Client.FactoryServiceReference.getScriptableMachinesRequest request) {
            return base.Channel.getScriptableMachines(request);
        }
        
        public System.Nullable<int>[] getScriptableMachines() {
            Client.FactoryServiceReference.getScriptableMachinesRequest inValue = new Client.FactoryServiceReference.getScriptableMachinesRequest();
            Client.FactoryServiceReference.getScriptableMachinesResponse retVal = ((Client.FactoryServiceReference.FactoryService)(this)).getScriptableMachines(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.FactoryServiceReference.rotateMachinesLeftResponse Client.FactoryServiceReference.FactoryService.rotateMachinesLeft(Client.FactoryServiceReference.rotateMachinesLeftRequest request) {
            return base.Channel.rotateMachinesLeft(request);
        }
        
        public void rotateMachinesLeft(long arg0, string[] arg1) {
            Client.FactoryServiceReference.rotateMachinesLeftRequest inValue = new Client.FactoryServiceReference.rotateMachinesLeftRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Client.FactoryServiceReference.rotateMachinesLeftResponse retVal = ((Client.FactoryServiceReference.FactoryService)(this)).rotateMachinesLeft(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.FactoryServiceReference.rotateMachinesRightResponse Client.FactoryServiceReference.FactoryService.rotateMachinesRight(Client.FactoryServiceReference.rotateMachinesRightRequest request) {
            return base.Channel.rotateMachinesRight(request);
        }
        
        public void rotateMachinesRight(long arg0, string[] arg1) {
            Client.FactoryServiceReference.rotateMachinesRightRequest inValue = new Client.FactoryServiceReference.rotateMachinesRightRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Client.FactoryServiceReference.rotateMachinesRightResponse retVal = ((Client.FactoryServiceReference.FactoryService)(this)).rotateMachinesRight(inValue);
        }
        
        public Client.FactoryServiceReference.machineMap getFactory(long arg0) {
            return base.Channel.getFactory(arg0);
        }
    }
}
