//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClientTest.LoginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.FactoryFactory.swtpro03.mi.hsrm.de/", ConfigurationName="LoginServiceReference.LoginService")]
    public interface LoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        long connect(string arg0, string arg1);
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoapClientTest.LoginServiceReference.getFactoriesResponse getFactories(SoapClientTest.LoginServiceReference.getFactoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool connectToFactory(long arg0, string arg1);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFactories", WrapperNamespace="http://services.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class getFactoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        public getFactoriesRequest() {
        }
        
        public getFactoriesRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFactoriesResponse", WrapperNamespace="http://services.FactoryFactory.swtpro03.mi.hsrm.de/", IsWrapped=true)]
    public partial class getFactoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("factories", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getFactoriesResponse() {
        }
        
        public getFactoriesResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceChannel : SoapClientTest.LoginServiceReference.LoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<SoapClientTest.LoginServiceReference.LoginService>, SoapClientTest.LoginServiceReference.LoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long connect(string arg0, string arg1) {
            return base.Channel.connect(arg0, arg1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClientTest.LoginServiceReference.getFactoriesResponse SoapClientTest.LoginServiceReference.LoginService.getFactories(SoapClientTest.LoginServiceReference.getFactoriesRequest request) {
            return base.Channel.getFactories(request);
        }
        
        public string[] getFactories(long arg0) {
            SoapClientTest.LoginServiceReference.getFactoriesRequest inValue = new SoapClientTest.LoginServiceReference.getFactoriesRequest();
            inValue.arg0 = arg0;
            SoapClientTest.LoginServiceReference.getFactoriesResponse retVal = ((SoapClientTest.LoginServiceReference.LoginService)(this)).getFactories(inValue);
            return retVal.@return;
        }
        
        public bool connectToFactory(long arg0, string arg1) {
            return base.Channel.connectToFactory(arg0, arg1);
        }
    }
}
