CC = gcc
CFLAGS = -g -ansi -Wall

all: WS010_1 WS010_2 stree2list WS010_5 WS012_1 WS012_2 WS012_3 leibniz encrypt remdup conlists addlists conlists2 conlists3 heron komprimier suchbaum test

WS010_1.o: WS010_1.c
	$(CC) -c $(CFLAGS) WS010_1.c -o WS010_1.o

WS010_1: WS010_1.o
	$(CC) $(CFLAGS) WS010_1.o -o WS010_1

WS010_2.o: WS010_2.c
	$(CC) -c $(CFLAGS) WS010_2.c -o WS010_2.o

WS010_2: WS010_2.o
	$(CC) $(CFLAGS) WS010_2.o -o WS010_2

stree2list.o: stree2list.c
	$(CC) -c $(CFLAGS) stree2list.c -o stree2list.o

stree2list: stree2list.o
	$(CC) $(CFLAGS) stree2list.o -o stree2list

WS010_5.o: WS010_5.c
	$(CC) -c $(CFLAGS) WS010_5.c -o WS010_5.o

WS010_5: WS010_5.o
	$(CC) $(CFLAGS) WS010_5.o -o WS010_5

WS012_1.o: WS012_1.c
	$(CC) -c $(CFLAGS) WS012_1.c -o WS012_1.o

WS012_1: WS012_1.o
	$(CC) $(CFLAGS) WS012_1.o -o WS012_1

WS012_2.o: WS012_2.c
	$(CC) -c $(CFLAGS) WS012_2.c -o WS012_2.o

WS012_2: WS012_2.o
	$(CC) $(CFLAGS) WS012_2.o -o WS012_2

WS012_3.o: WS012_3.c
	$(CC) -c $(CFLAGS) WS012_3.c -o WS012_3.o

WS012_3: WS012_3.o
	$(CC) $(CFLAGS) WS012_3.o -o WS012_3

leibniz.o: leibniz.c
	$(CC) -c $(CFLAGS) leibniz.c -o leibniz.o

leibniz: leibniz.o
	$(CC) $(CFLAGS) leibniz.o -o leibniz

encrypt.o: encrypt.c
	$(CC) -c $(CFLAGS) encrypt.c -o encrypt.o

encrypt: encrypt.o
	$(CC) $(CFLAGS) encrypt.o -o encrypt

remdup.o: remdup.c
	$(CC) -c $(CFLAGS) remdup.c -o remdup.o

remdup: remdup.o
	$(CC) $(CFLAGS) remdup.o -o remdup

conlists.o: conlists.c
	$(CC) -c $(CFLAGS) conlists.c -o conlists.o

conlists: conlists.o
	$(CC) $(CFLAGS) conlists.o -o conlists

addlists.o: addlists.c
	$(CC) -c $(CFLAGS) addlists.c -o addlists.o

addlists: addlists.o
	$(CC) $(CFLAGS) addlists.o -o addlists

conlists2.o: conlists2.c
	$(CC) -c $(CFLAGS) conlists2.c -o conlists2.o

conlists2: conlists2.o
	$(CC) $(CFLAGS) conlists2.o -o conlists2

conlists3.o: conlists3.c
	$(CC) -c $(CFLAGS) conlists3.c -o conlists3.o

conlists3: conlists3.o
	$(CC) $(CFLAGS) conlists3.o -o conlists3

heron.o: heron.c
	$(CC) -c $(CFLAGS) heron.c -o heron.o

heron: heron.o
	$(CC) $(CFLAGS) heron.o -o heron

komprimier.o: komprimier.c
	$(CC) -c $(CFLAGS) komprimier.c -o komprimier.o

komprimier: komprimier.o
	$(CC) $(CFLAGS) komprimier.o -o komprimier

suchbaum.o: suchbaum.c
	$(CC) -c $(CFLAGS) suchbaum.c -o suchbaum.o

suchbaum: suchbaum.o
	$(CC) $(CFLAGS) suchbaum.o -o suchbaum

test.o: test.c
	$(CC) -c $(CFLAGS) test.c -o test.o

test: test.o
	$(CC) $(CFLAGS) test.o -o test